server:
  port: 8888
  servlet:
    context-path: /xjforum
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 19970822

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # \u4E0B\u9762\u4E3A\u8FDE\u63A5\u6C60\u7684\u8865\u5145\u8BBE\u7F6E\uFF0C\u5E94\u7528\u5230\u4E0A\u9762\u6240\u6709\u6570\u636E\u6E90\u4E2D
      # \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
      initialSize: 1
      minIdle: 3
      maxActive: 20
        # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
        #maxWait: 60000
        # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
        #timeBetweenEvictionRunsMillis: 60000
        # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      #minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false #\u81EA\u52A8\u521B\u5EFA\u8868
    hibernate:
      ddl-auto: none #\u521B\u5EFA\u65B9\u5F0F
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate :
        dialect : org.hibernate.dialect.MySQL5Dialect
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
swagger:
  enabled : true

